name: Packaging for Windows
on: workflow_dispatch # manually triggered
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: Install WiX Toolset
#        run: choco install --force -y wixtoolset
#      - name: Install Inno Setup
#        run: choco install --force -y innosetup
      - name: Package app
        run: mvn clean package
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Setup Installer (.exe)
          path: target/HelloWorldMaven_*.exe
      - uses: actions/upload-artifact@v2
        with:
          name: Windows MSI Installer (.msi)
          path: target/HelloWorldMaven_*.msi
